/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Contract {
  'id' : bigint,
  'status' : ContractStatus,
  'terms' : string,
  'serviceType' : string,
  'serviceDetails' : string,
  'clientName' : string,
  'totalPriceRobux' : bigint,
  'createdAt' : bigint,
  'clientDiscord' : string,
  'signatureText' : string,
  'caller' : Principal,
  'totalPriceUSD' : number,
}
export type ContractStatus = { 'Draft' : null } |
  { 'Signed' : null } |
  { 'Completed' : null };
export type ExternalBlob = Uint8Array;
export interface FreeRelease {
  'id' : bigint,
  'title' : string,
  'isPublished' : boolean,
  'file' : ExternalBlob,
  'createdAt' : bigint,
  'description' : string,
  'category' : string,
  'downloadCount' : bigint,
}
export interface GalleryItem {
  'id' : bigint,
  'title' : string,
  'isPublished' : boolean,
  'createdAt' : bigint,
  'description' : string,
  'category' : string,
  'image' : ExternalBlob,
}
export interface Inquiry {
  'id' : bigint,
  'status' : InquiryStatus,
  'serviceName' : string,
  'clientName' : string,
  'customDetails' : string,
  'submittedAt' : bigint,
  'priceRobux' : bigint,
  'clientDiscord' : string,
  'caller' : Principal,
  'serviceId' : bigint,
  'priceUSD' : number,
  'adminNotes' : string,
}
export type InquiryStatus = { 'InReview' : null } |
  { 'Cancelled' : null } |
  { 'Completed' : null } |
  { 'Pending' : null };
export interface Service {
  'id' : bigint,
  'name' : string,
  'isAvailable' : boolean,
  'description' : string,
  'inclusions' : Array<string>,
  'priceRobux' : bigint,
  'category' : ServiceCategory,
  'priceUSD' : number,
}
export type ServiceCategory = { 'ELS' : null } |
  { 'Livery' : null } |
  { 'CommunitySetup' : null } |
  { 'BotDevelopment' : null } |
  { 'Graphics' : null };
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _ImmutableObjectStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _ImmutableObjectStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _ImmutableObjectStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_immutableObjectStorageBlobsAreLive' : ActorMethod<
    [Array<Uint8Array>],
    Array<boolean>
  >,
  '_immutableObjectStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_immutableObjectStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_immutableObjectStorageCreateCertificate' : ActorMethod<
    [string],
    _ImmutableObjectStorageCreateCertificateResult
  >,
  '_immutableObjectStorageRefillCashier' : ActorMethod<
    [[] | [_ImmutableObjectStorageRefillInformation]],
    _ImmutableObjectStorageRefillResult
  >,
  '_immutableObjectStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'addFreeRelease' : ActorMethod<
    [string, string, string, ExternalBlob, boolean],
    FreeRelease
  >,
  'addGalleryItem' : ActorMethod<
    [string, string, string, ExternalBlob, boolean],
    GalleryItem
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createContract' : ActorMethod<
    [string, string, string, string, number, bigint, string],
    Contract
  >,
  'deleteFreeRelease' : ActorMethod<[bigint], boolean>,
  'deleteGalleryItem' : ActorMethod<[bigint], boolean>,
  'getAllContracts' : ActorMethod<[], Array<Contract>>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getFreeReleases' : ActorMethod<[], Array<FreeRelease>>,
  'getGalleryItems' : ActorMethod<[], Array<GalleryItem>>,
  'getInquiries' : ActorMethod<[], Array<Inquiry>>,
  'getMyContracts' : ActorMethod<[], Array<Contract>>,
  'getMyInquiries' : ActorMethod<[], Array<Inquiry>>,
  'getServices' : ActorMethod<[], Array<Service>>,
  'getServicesByCategory' : ActorMethod<[ServiceCategory], Array<Service>>,
  'incrementDownloadCount' : ActorMethod<[bigint], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'signContract' : ActorMethod<[bigint, string], boolean>,
  'submitInquiry' : ActorMethod<
    [string, string, bigint, string, string, number, bigint],
    Inquiry
  >,
  'updateInquiryStatus' : ActorMethod<[bigint, InquiryStatus, string], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];