/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _ImmutableObjectStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _ImmutableObjectStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const FreeRelease = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'isPublished' : IDL.Bool,
  'file' : ExternalBlob,
  'createdAt' : IDL.Int,
  'description' : IDL.Text,
  'category' : IDL.Text,
  'downloadCount' : IDL.Nat,
});
export const GalleryItem = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'isPublished' : IDL.Bool,
  'createdAt' : IDL.Int,
  'description' : IDL.Text,
  'category' : IDL.Text,
  'image' : ExternalBlob,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ContractStatus = IDL.Variant({
  'Draft' : IDL.Null,
  'Signed' : IDL.Null,
  'Completed' : IDL.Null,
});
export const Contract = IDL.Record({
  'id' : IDL.Nat,
  'status' : ContractStatus,
  'terms' : IDL.Text,
  'serviceType' : IDL.Text,
  'serviceDetails' : IDL.Text,
  'clientName' : IDL.Text,
  'totalPriceRobux' : IDL.Nat,
  'createdAt' : IDL.Int,
  'clientDiscord' : IDL.Text,
  'signatureText' : IDL.Text,
  'caller' : IDL.Principal,
  'totalPriceUSD' : IDL.Float64,
});
export const InquiryStatus = IDL.Variant({
  'InReview' : IDL.Null,
  'Cancelled' : IDL.Null,
  'Completed' : IDL.Null,
  'Pending' : IDL.Null,
});
export const Inquiry = IDL.Record({
  'id' : IDL.Nat,
  'status' : InquiryStatus,
  'serviceName' : IDL.Text,
  'clientName' : IDL.Text,
  'customDetails' : IDL.Text,
  'submittedAt' : IDL.Int,
  'priceRobux' : IDL.Nat,
  'clientDiscord' : IDL.Text,
  'caller' : IDL.Principal,
  'serviceId' : IDL.Nat,
  'priceUSD' : IDL.Float64,
  'adminNotes' : IDL.Text,
});
export const ServiceCategory = IDL.Variant({
  'ELS' : IDL.Null,
  'Livery' : IDL.Null,
  'CommunitySetup' : IDL.Null,
  'BotDevelopment' : IDL.Null,
  'Graphics' : IDL.Null,
});
export const Service = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'isAvailable' : IDL.Bool,
  'description' : IDL.Text,
  'inclusions' : IDL.Vec(IDL.Text),
  'priceRobux' : IDL.Nat,
  'category' : ServiceCategory,
  'priceUSD' : IDL.Float64,
});

export const idlService = IDL.Service({
  '_immutableObjectStorageBlobsAreLive' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [IDL.Vec(IDL.Bool)],
      ['query'],
    ),
  '_immutableObjectStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_immutableObjectStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_ImmutableObjectStorageCreateCertificateResult],
      [],
    ),
  '_immutableObjectStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
      [_ImmutableObjectStorageRefillResult],
      [],
    ),
  '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControl' : IDL.Func([], [], []),
  'addFreeRelease' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, ExternalBlob, IDL.Bool],
      [FreeRelease],
      [],
    ),
  'addGalleryItem' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, ExternalBlob, IDL.Bool],
      [GalleryItem],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createContract' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Float64, IDL.Nat, IDL.Text],
      [Contract],
      [],
    ),
  'deleteFreeRelease' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteGalleryItem' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'getAllContracts' : IDL.Func([], [IDL.Vec(Contract)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getFreeReleases' : IDL.Func([], [IDL.Vec(FreeRelease)], ['query']),
  'getGalleryItems' : IDL.Func([], [IDL.Vec(GalleryItem)], ['query']),
  'getInquiries' : IDL.Func([], [IDL.Vec(Inquiry)], ['query']),
  'getMyContracts' : IDL.Func([], [IDL.Vec(Contract)], ['query']),
  'getMyInquiries' : IDL.Func([], [IDL.Vec(Inquiry)], ['query']),
  'getServices' : IDL.Func([], [IDL.Vec(Service)], ['query']),
  'getServicesByCategory' : IDL.Func(
      [ServiceCategory],
      [IDL.Vec(Service)],
      ['query'],
    ),
  'incrementDownloadCount' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'signContract' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Bool], []),
  'submitInquiry' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Text, IDL.Float64, IDL.Nat],
      [Inquiry],
      [],
    ),
  'updateInquiryStatus' : IDL.Func(
      [IDL.Nat, InquiryStatus, IDL.Text],
      [IDL.Bool],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _ImmutableObjectStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _ImmutableObjectStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const FreeRelease = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'isPublished' : IDL.Bool,
    'file' : ExternalBlob,
    'createdAt' : IDL.Int,
    'description' : IDL.Text,
    'category' : IDL.Text,
    'downloadCount' : IDL.Nat,
  });
  const GalleryItem = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'isPublished' : IDL.Bool,
    'createdAt' : IDL.Int,
    'description' : IDL.Text,
    'category' : IDL.Text,
    'image' : ExternalBlob,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ContractStatus = IDL.Variant({
    'Draft' : IDL.Null,
    'Signed' : IDL.Null,
    'Completed' : IDL.Null,
  });
  const Contract = IDL.Record({
    'id' : IDL.Nat,
    'status' : ContractStatus,
    'terms' : IDL.Text,
    'serviceType' : IDL.Text,
    'serviceDetails' : IDL.Text,
    'clientName' : IDL.Text,
    'totalPriceRobux' : IDL.Nat,
    'createdAt' : IDL.Int,
    'clientDiscord' : IDL.Text,
    'signatureText' : IDL.Text,
    'caller' : IDL.Principal,
    'totalPriceUSD' : IDL.Float64,
  });
  const InquiryStatus = IDL.Variant({
    'InReview' : IDL.Null,
    'Cancelled' : IDL.Null,
    'Completed' : IDL.Null,
    'Pending' : IDL.Null,
  });
  const Inquiry = IDL.Record({
    'id' : IDL.Nat,
    'status' : InquiryStatus,
    'serviceName' : IDL.Text,
    'clientName' : IDL.Text,
    'customDetails' : IDL.Text,
    'submittedAt' : IDL.Int,
    'priceRobux' : IDL.Nat,
    'clientDiscord' : IDL.Text,
    'caller' : IDL.Principal,
    'serviceId' : IDL.Nat,
    'priceUSD' : IDL.Float64,
    'adminNotes' : IDL.Text,
  });
  const ServiceCategory = IDL.Variant({
    'ELS' : IDL.Null,
    'Livery' : IDL.Null,
    'CommunitySetup' : IDL.Null,
    'BotDevelopment' : IDL.Null,
    'Graphics' : IDL.Null,
  });
  const Service = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'isAvailable' : IDL.Bool,
    'description' : IDL.Text,
    'inclusions' : IDL.Vec(IDL.Text),
    'priceRobux' : IDL.Nat,
    'category' : ServiceCategory,
    'priceUSD' : IDL.Float64,
  });
  
  return IDL.Service({
    '_immutableObjectStorageBlobsAreLive' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [IDL.Vec(IDL.Bool)],
        ['query'],
      ),
    '_immutableObjectStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_immutableObjectStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_ImmutableObjectStorageCreateCertificateResult],
        [],
      ),
    '_immutableObjectStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
        [_ImmutableObjectStorageRefillResult],
        [],
      ),
    '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControl' : IDL.Func([], [], []),
    'addFreeRelease' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, ExternalBlob, IDL.Bool],
        [FreeRelease],
        [],
      ),
    'addGalleryItem' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, ExternalBlob, IDL.Bool],
        [GalleryItem],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createContract' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Float64,
          IDL.Nat,
          IDL.Text,
        ],
        [Contract],
        [],
      ),
    'deleteFreeRelease' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteGalleryItem' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'getAllContracts' : IDL.Func([], [IDL.Vec(Contract)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getFreeReleases' : IDL.Func([], [IDL.Vec(FreeRelease)], ['query']),
    'getGalleryItems' : IDL.Func([], [IDL.Vec(GalleryItem)], ['query']),
    'getInquiries' : IDL.Func([], [IDL.Vec(Inquiry)], ['query']),
    'getMyContracts' : IDL.Func([], [IDL.Vec(Contract)], ['query']),
    'getMyInquiries' : IDL.Func([], [IDL.Vec(Inquiry)], ['query']),
    'getServices' : IDL.Func([], [IDL.Vec(Service)], ['query']),
    'getServicesByCategory' : IDL.Func(
        [ServiceCategory],
        [IDL.Vec(Service)],
        ['query'],
      ),
    'incrementDownloadCount' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'signContract' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Bool], []),
    'submitInquiry' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Text, IDL.Float64, IDL.Nat],
        [Inquiry],
        [],
      ),
    'updateInquiryStatus' : IDL.Func(
        [IDL.Nat, InquiryStatus, IDL.Text],
        [IDL.Bool],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };