/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Contract {
    id: bigint;
    status: ContractStatus;
    terms: string;
    serviceType: string;
    serviceDetails: string;
    clientName: string;
    totalPriceRobux: bigint;
    createdAt: bigint;
    clientDiscord: string;
    signatureText: string;
    caller: Principal;
    totalPriceUSD: number;
}
export interface _ImmutableObjectStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface Service {
    id: bigint;
    name: string;
    isAvailable: boolean;
    description: string;
    inclusions: Array<string>;
    priceRobux: bigint;
    category: ServiceCategory;
    priceUSD: number;
}
export interface _ImmutableObjectStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface Inquiry {
    id: bigint;
    status: InquiryStatus;
    serviceName: string;
    clientName: string;
    customDetails: string;
    submittedAt: bigint;
    priceRobux: bigint;
    clientDiscord: string;
    caller: Principal;
    serviceId: bigint;
    priceUSD: number;
    adminNotes: string;
}
export interface GalleryItem {
    id: bigint;
    title: string;
    isPublished: boolean;
    createdAt: bigint;
    description: string;
    category: string;
    image: ExternalBlob;
}
export interface FreeRelease {
    id: bigint;
    title: string;
    isPublished: boolean;
    file: ExternalBlob;
    createdAt: bigint;
    description: string;
    category: string;
    downloadCount: bigint;
}
export interface _ImmutableObjectStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export enum ContractStatus {
    Draft = "Draft",
    Signed = "Signed",
    Completed = "Completed"
}
export enum InquiryStatus {
    InReview = "InReview",
    Cancelled = "Cancelled",
    Completed = "Completed",
    Pending = "Pending"
}
export enum ServiceCategory {
    ELS = "ELS",
    Livery = "Livery",
    CommunitySetup = "CommunitySetup",
    BotDevelopment = "BotDevelopment",
    Graphics = "Graphics"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _immutableObjectStorageBlobsAreLive(hashes: Array<Uint8Array>): Promise<Array<boolean>>;
    _immutableObjectStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _immutableObjectStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _immutableObjectStorageCreateCertificate(blobHash: string): Promise<_ImmutableObjectStorageCreateCertificateResult>;
    _immutableObjectStorageRefillCashier(refillInformation: _ImmutableObjectStorageRefillInformation | null): Promise<_ImmutableObjectStorageRefillResult>;
    _immutableObjectStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControl(): Promise<void>;
    addFreeRelease(title: string, description: string, category: string, file: ExternalBlob, isPublished: boolean): Promise<FreeRelease>;
    addGalleryItem(title: string, description: string, category: string, image: ExternalBlob, isPublished: boolean): Promise<GalleryItem>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createContract(clientName: string, clientDiscord: string, serviceType: string, serviceDetails: string, totalPriceUSD: number, totalPriceRobux: bigint, terms: string): Promise<Contract>;
    deleteFreeRelease(id: bigint): Promise<boolean>;
    deleteGalleryItem(id: bigint): Promise<boolean>;
    getAllContracts(): Promise<Array<Contract>>;
    getCallerUserRole(): Promise<UserRole>;
    getFreeReleases(): Promise<Array<FreeRelease>>;
    getGalleryItems(): Promise<Array<GalleryItem>>;
    getInquiries(): Promise<Array<Inquiry>>;
    getMyContracts(): Promise<Array<Contract>>;
    getMyInquiries(): Promise<Array<Inquiry>>;
    getServices(): Promise<Array<Service>>;
    getServicesByCategory(category: ServiceCategory): Promise<Array<Service>>;
    incrementDownloadCount(id: bigint): Promise<boolean>;
    isCallerAdmin(): Promise<boolean>;
    signContract(id: bigint, signatureText: string): Promise<boolean>;
    submitInquiry(clientName: string, clientDiscord: string, serviceId: bigint, serviceName: string, customDetails: string, priceUSD: number, priceRobux: bigint): Promise<Inquiry>;
    updateInquiryStatus(id: bigint, status: InquiryStatus, notes: string): Promise<boolean>;
}
import type { Contract as _Contract, ContractStatus as _ContractStatus, ExternalBlob as _ExternalBlob, FreeRelease as _FreeRelease, GalleryItem as _GalleryItem, Inquiry as _Inquiry, InquiryStatus as _InquiryStatus, Service as _Service, ServiceCategory as _ServiceCategory, UserRole as _UserRole, _ImmutableObjectStorageRefillInformation as __ImmutableObjectStorageRefillInformation, _ImmutableObjectStorageRefillResult as __ImmutableObjectStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _immutableObjectStorageBlobsAreLive(arg0: Array<Uint8Array>): Promise<Array<boolean>> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageBlobsAreLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageBlobsAreLive(arg0);
            return result;
        }
    }
    async _immutableObjectStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageBlobsToDelete();
            return result;
        }
    }
    async _immutableObjectStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _immutableObjectStorageCreateCertificate(arg0: string): Promise<_ImmutableObjectStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _immutableObjectStorageRefillCashier(arg0: _ImmutableObjectStorageRefillInformation | null): Promise<_ImmutableObjectStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__ImmutableObjectStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__ImmutableObjectStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _immutableObjectStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControl();
            return result;
        }
    }
    async addFreeRelease(arg0: string, arg1: string, arg2: string, arg3: ExternalBlob, arg4: boolean): Promise<FreeRelease> {
        if (this.processError) {
            try {
                const result = await this.actor.addFreeRelease(arg0, arg1, arg2, await to_candid_ExternalBlob_n8(this._uploadFile, this._downloadFile, arg3), arg4);
                return from_candid_FreeRelease_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addFreeRelease(arg0, arg1, arg2, await to_candid_ExternalBlob_n8(this._uploadFile, this._downloadFile, arg3), arg4);
            return from_candid_FreeRelease_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async addGalleryItem(arg0: string, arg1: string, arg2: string, arg3: ExternalBlob, arg4: boolean): Promise<GalleryItem> {
        if (this.processError) {
            try {
                const result = await this.actor.addGalleryItem(arg0, arg1, arg2, await to_candid_ExternalBlob_n8(this._uploadFile, this._downloadFile, arg3), arg4);
                return from_candid_GalleryItem_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addGalleryItem(arg0, arg1, arg2, await to_candid_ExternalBlob_n8(this._uploadFile, this._downloadFile, arg3), arg4);
            return from_candid_GalleryItem_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n14(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n14(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createContract(arg0: string, arg1: string, arg2: string, arg3: string, arg4: number, arg5: bigint, arg6: string): Promise<Contract> {
        if (this.processError) {
            try {
                const result = await this.actor.createContract(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
                return from_candid_Contract_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createContract(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
            return from_candid_Contract_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteFreeRelease(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteFreeRelease(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteFreeRelease(arg0);
            return result;
        }
    }
    async deleteGalleryItem(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteGalleryItem(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteGalleryItem(arg0);
            return result;
        }
    }
    async getAllContracts(): Promise<Array<Contract>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllContracts();
                return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllContracts();
            return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFreeReleases(): Promise<Array<FreeRelease>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFreeReleases();
                return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFreeReleases();
            return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getGalleryItems(): Promise<Array<GalleryItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getGalleryItems();
                return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGalleryItems();
            return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getInquiries(): Promise<Array<Inquiry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getInquiries();
                return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInquiries();
            return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyContracts(): Promise<Array<Contract>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyContracts();
                return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyContracts();
            return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyInquiries(): Promise<Array<Inquiry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyInquiries();
                return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyInquiries();
            return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getServices(): Promise<Array<Service>> {
        if (this.processError) {
            try {
                const result = await this.actor.getServices();
                return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getServices();
            return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getServicesByCategory(arg0: ServiceCategory): Promise<Array<Service>> {
        if (this.processError) {
            try {
                const result = await this.actor.getServicesByCategory(to_candid_ServiceCategory_n35(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getServicesByCategory(to_candid_ServiceCategory_n35(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async incrementDownloadCount(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.incrementDownloadCount(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.incrementDownloadCount(arg0);
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async signContract(arg0: bigint, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.signContract(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.signContract(arg0, arg1);
            return result;
        }
    }
    async submitInquiry(arg0: string, arg1: string, arg2: bigint, arg3: string, arg4: string, arg5: number, arg6: bigint): Promise<Inquiry> {
        if (this.processError) {
            try {
                const result = await this.actor.submitInquiry(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
                return from_candid_Inquiry_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitInquiry(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
            return from_candid_Inquiry_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateInquiryStatus(arg0: bigint, arg1: InquiryStatus, arg2: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateInquiryStatus(arg0, to_candid_InquiryStatus_n37(this._uploadFile, this._downloadFile, arg1), arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateInquiryStatus(arg0, to_candid_InquiryStatus_n37(this._uploadFile, this._downloadFile, arg1), arg2);
            return result;
        }
    }
}
function from_candid_ContractStatus_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ContractStatus): ContractStatus {
    return from_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function from_candid_Contract_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Contract): Contract {
    return from_candid_record_n17(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
async function from_candid_FreeRelease_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FreeRelease): Promise<FreeRelease> {
    return await from_candid_record_n10(_uploadFile, _downloadFile, value);
}
async function from_candid_GalleryItem_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _GalleryItem): Promise<GalleryItem> {
    return await from_candid_record_n13(_uploadFile, _downloadFile, value);
}
function from_candid_InquiryStatus_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _InquiryStatus): InquiryStatus {
    return from_candid_variant_n29(_uploadFile, _downloadFile, value);
}
function from_candid_Inquiry_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Inquiry): Inquiry {
    return from_candid_record_n27(_uploadFile, _downloadFile, value);
}
function from_candid_ServiceCategory_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ServiceCategory): ServiceCategory {
    return from_candid_variant_n34(_uploadFile, _downloadFile, value);
}
function from_candid_Service_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Service): Service {
    return from_candid_record_n32(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n22(_uploadFile, _downloadFile, value);
}
function from_candid__ImmutableObjectStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __ImmutableObjectStorageRefillResult): _ImmutableObjectStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    title: string;
    isPublished: boolean;
    file: _ExternalBlob;
    createdAt: bigint;
    description: string;
    category: string;
    downloadCount: bigint;
}): Promise<{
    id: bigint;
    title: string;
    isPublished: boolean;
    file: ExternalBlob;
    createdAt: bigint;
    description: string;
    category: string;
    downloadCount: bigint;
}> {
    return {
        id: value.id,
        title: value.title,
        isPublished: value.isPublished,
        file: await from_candid_ExternalBlob_n11(_uploadFile, _downloadFile, value.file),
        createdAt: value.createdAt,
        description: value.description,
        category: value.category,
        downloadCount: value.downloadCount
    };
}
async function from_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    title: string;
    isPublished: boolean;
    createdAt: bigint;
    description: string;
    category: string;
    image: _ExternalBlob;
}): Promise<{
    id: bigint;
    title: string;
    isPublished: boolean;
    createdAt: bigint;
    description: string;
    category: string;
    image: ExternalBlob;
}> {
    return {
        id: value.id,
        title: value.title,
        isPublished: value.isPublished,
        createdAt: value.createdAt,
        description: value.description,
        category: value.category,
        image: await from_candid_ExternalBlob_n11(_uploadFile, _downloadFile, value.image)
    };
}
function from_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _ContractStatus;
    terms: string;
    serviceType: string;
    serviceDetails: string;
    clientName: string;
    totalPriceRobux: bigint;
    createdAt: bigint;
    clientDiscord: string;
    signatureText: string;
    caller: Principal;
    totalPriceUSD: number;
}): {
    id: bigint;
    status: ContractStatus;
    terms: string;
    serviceType: string;
    serviceDetails: string;
    clientName: string;
    totalPriceRobux: bigint;
    createdAt: bigint;
    clientDiscord: string;
    signatureText: string;
    caller: Principal;
    totalPriceUSD: number;
} {
    return {
        id: value.id,
        status: from_candid_ContractStatus_n18(_uploadFile, _downloadFile, value.status),
        terms: value.terms,
        serviceType: value.serviceType,
        serviceDetails: value.serviceDetails,
        clientName: value.clientName,
        totalPriceRobux: value.totalPriceRobux,
        createdAt: value.createdAt,
        clientDiscord: value.clientDiscord,
        signatureText: value.signatureText,
        caller: value.caller,
        totalPriceUSD: value.totalPriceUSD
    };
}
function from_candid_record_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _InquiryStatus;
    serviceName: string;
    clientName: string;
    customDetails: string;
    submittedAt: bigint;
    priceRobux: bigint;
    clientDiscord: string;
    caller: Principal;
    serviceId: bigint;
    priceUSD: number;
    adminNotes: string;
}): {
    id: bigint;
    status: InquiryStatus;
    serviceName: string;
    clientName: string;
    customDetails: string;
    submittedAt: bigint;
    priceRobux: bigint;
    clientDiscord: string;
    caller: Principal;
    serviceId: bigint;
    priceUSD: number;
    adminNotes: string;
} {
    return {
        id: value.id,
        status: from_candid_InquiryStatus_n28(_uploadFile, _downloadFile, value.status),
        serviceName: value.serviceName,
        clientName: value.clientName,
        customDetails: value.customDetails,
        submittedAt: value.submittedAt,
        priceRobux: value.priceRobux,
        clientDiscord: value.clientDiscord,
        caller: value.caller,
        serviceId: value.serviceId,
        priceUSD: value.priceUSD,
        adminNotes: value.adminNotes
    };
}
function from_candid_record_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    name: string;
    isAvailable: boolean;
    description: string;
    inclusions: Array<string>;
    priceRobux: bigint;
    category: _ServiceCategory;
    priceUSD: number;
}): {
    id: bigint;
    name: string;
    isAvailable: boolean;
    description: string;
    inclusions: Array<string>;
    priceRobux: bigint;
    category: ServiceCategory;
    priceUSD: number;
} {
    return {
        id: value.id,
        name: value.name,
        isAvailable: value.isAvailable,
        description: value.description,
        inclusions: value.inclusions,
        priceRobux: value.priceRobux,
        category: from_candid_ServiceCategory_n33(_uploadFile, _downloadFile, value.category),
        priceUSD: value.priceUSD
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Draft: null;
} | {
    Signed: null;
} | {
    Completed: null;
}): ContractStatus {
    return "Draft" in value ? ContractStatus.Draft : "Signed" in value ? ContractStatus.Signed : "Completed" in value ? ContractStatus.Completed : value;
}
function from_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    InReview: null;
} | {
    Cancelled: null;
} | {
    Completed: null;
} | {
    Pending: null;
}): InquiryStatus {
    return "InReview" in value ? InquiryStatus.InReview : "Cancelled" in value ? InquiryStatus.Cancelled : "Completed" in value ? InquiryStatus.Completed : "Pending" in value ? InquiryStatus.Pending : value;
}
function from_candid_variant_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ELS: null;
} | {
    Livery: null;
} | {
    CommunitySetup: null;
} | {
    BotDevelopment: null;
} | {
    Graphics: null;
}): ServiceCategory {
    return "ELS" in value ? ServiceCategory.ELS : "Livery" in value ? ServiceCategory.Livery : "CommunitySetup" in value ? ServiceCategory.CommunitySetup : "BotDevelopment" in value ? ServiceCategory.BotDevelopment : "Graphics" in value ? ServiceCategory.Graphics : value;
}
function from_candid_vec_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Contract>): Array<Contract> {
    return value.map((x)=>from_candid_Contract_n16(_uploadFile, _downloadFile, x));
}
async function from_candid_vec_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_FreeRelease>): Promise<Array<FreeRelease>> {
    return await Promise.all(value.map(async (x)=>await from_candid_FreeRelease_n9(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_GalleryItem>): Promise<Array<GalleryItem>> {
    return await Promise.all(value.map(async (x)=>await from_candid_GalleryItem_n12(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Inquiry>): Array<Inquiry> {
    return value.map((x)=>from_candid_Inquiry_n26(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Service>): Array<Service> {
    return value.map((x)=>from_candid_Service_n31(_uploadFile, _downloadFile, x));
}
async function to_candid_ExternalBlob_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_InquiryStatus_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: InquiryStatus): _InquiryStatus {
    return to_candid_variant_n38(_uploadFile, _downloadFile, value);
}
function to_candid_ServiceCategory_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ServiceCategory): _ServiceCategory {
    return to_candid_variant_n36(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function to_candid__ImmutableObjectStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ImmutableObjectStorageRefillInformation): __ImmutableObjectStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ImmutableObjectStorageRefillInformation | null): [] | [__ImmutableObjectStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__ImmutableObjectStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ServiceCategory): {
    ELS: null;
} | {
    Livery: null;
} | {
    CommunitySetup: null;
} | {
    BotDevelopment: null;
} | {
    Graphics: null;
} {
    return value == ServiceCategory.ELS ? {
        ELS: null
    } : value == ServiceCategory.Livery ? {
        Livery: null
    } : value == ServiceCategory.CommunitySetup ? {
        CommunitySetup: null
    } : value == ServiceCategory.BotDevelopment ? {
        BotDevelopment: null
    } : value == ServiceCategory.Graphics ? {
        Graphics: null
    } : value;
}
function to_candid_variant_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: InquiryStatus): {
    InReview: null;
} | {
    Cancelled: null;
} | {
    Completed: null;
} | {
    Pending: null;
} {
    return value == InquiryStatus.InReview ? {
        InReview: null
    } : value == InquiryStatus.Cancelled ? {
        Cancelled: null
    } : value == InquiryStatus.Completed ? {
        Completed: null
    } : value == InquiryStatus.Pending ? {
        Pending: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
